"""
Django settings for HelloWorld project.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'p4s-ewqu!g12=tu@p9*#jc)s8ix+_qi4*p+v_e90$h8bv7m2@x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'books',

    
)
#MIDDLEWARE_CLASSES
MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',#自己添加(2018.05.23,为了admin网站显示中文)
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',#解决post(403),csrf验证
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
]

ROOT_URLCONF = 'HelloWorld.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates').replace('\\','/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                # "django.core.context_processors.request",
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'HelloWorld.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mydb',
        'USER' : 'root',
        'PASSWORD': '123456',
        'HOST' : '127.0.0.1',
        'PORT ': '3306',
    }
}
#'ENGINE': 'django.db.backends.sqlite3',
#'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

#设置session
SESSION_COOKIE_AGE = 60*60*24
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL ='/static/'#os.path.join(os.path.dirname(__file__),'static')
STATICFILES_DIRS=(BASE_DIR,'static')

MEDIA_ROOT=os.path.join(BASE_DIR,"media")
#media是约定成俗的文件夹名
MEDIA_URL="/media/"   # 跟STATIC_URL类似，指定用户可以通过这个路径找到文件

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATICFILES_DIRS=(
#     # os.path.join(BASE_DIR,'static'),
#     # os.path.join(BASE_DIR, "recommend", "static"),
    
#     ("css",os.path.join(STATIC_ROOT,'css')),
#     ("js",os.path.join(STATIC_ROOT,'js')),
#     ("images",os.path.join(STATIC_ROOT,'images')),
    
# )
EMAIL_HOST = 'smtp.sina.com.cn'
EMAIL_PORT = 80
EMAIL_HOST_USER = 'damochar@sina.com'
EMAIL_HOST_PASSWORD = 'liaotianshi123'
EMAIL_USE_TLS = False
EMAIL_FROM = 'damochar@sina.com'